# -*- coding: utf-8 -*-
"""Copy of FinalProject_Carter_Daniel_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MoQ-bdd3WXHl3j1oYPl9m-vBVtlW5sLp

# Final Project - DSCI 619 - Image Classification & Sentiment Analysis
## Part I - Image Classification
"""

from google.colab import drive
drive.mount('/content/drive')

#Install Kera-Tuner
!pip install keras-tuner

# Commented out IPython magic to ensure Python compatibility.
# IMPORT LIBRARIES and PACKAGES
from __future__ import absolute_import, division, print_function, unicode_literals
from collections import Counter

import os
import re
import random
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import PIL #Python Imaging Library

import tensorflow as tf
import tensorflow.compat.v2 as tf
import tensorflow_datasets as tfds
#tfds.disable_progress_bar()

from glob import glob
from tensorflow import keras
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, Dropout, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from IPython.display import display  # display images
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import kerastuner as kt

# %matplotlib inline

"""# PART I - IMAGE CLASSIFICATION - 3 CNN Models

AI company has a 2 GB dataset containing over 15,000 images of indoor locations. Originally from MIT, this dataset was built to work on indoor scene recognition. There are 67 categories of JPEG images. The number of images per category varies, but there are at least 100 images for each category.

Data was obtained from:
https://www.kaggle.com/itsahmad/indoor-scenes-cvpr-2019

**Please download the dataset from the link above and unzip it into a folder.**

## Assign Path to Previously Downloaded Images or Download Images
"""

import pathlib

# set the parent folder that contains the subfolders that are the labels
img_dir = pathlib.Path(r"/content/drive/MyDrive/COSC_640/Images")
print(f"The indoorCVPR_09 photos are stored in local directory: {img_dir}")

"""## List the directories to double-check"""

total_files = 0
for root, dirs, files in os.walk(str(img_dir)):
    level = root.replace(str(img_dir), '').count(os.sep)
    indent = ' ' * 4 * (level)
    print(f'{indent}{os.path.basename(root)}/ ({len(files)} files)')
    total_files += len(files)
print(f'There are {total_files -1} images in this dataset')

"""## Get the Indoor Image label using the Image directory"""

IndoorImage_dir = [ name for name in list(os.listdir(img_dir)) if os.path.isdir(os.path.join(img_dir, name)) ]
print(f' The Indoor Image labels = {IndoorImage_dir}')

# SORT the directories in alphabetical order
IndoorImage_dir.sort()
print(f'\n The SORTED Indoor Image labels = {IndoorImage_dir}')

print(f'\nThere are {len(IndoorImage_dir)} classes of Indoor Images.') ### There are  (67) classes of Indoor Images.

"""# Please check the images quality and remove the bad images if neccessary

If we don't remove the bad images, the codes will crash and produce errors.

Deleted the bad folders before loading the data. Going to
"""

# import glob
# img_dir = '/content/drive/MyDrive/COSC_640/Images'
# img_paths = glob.glob(os.path.join(img_dir,'*/*.*')) # assuming you point to the directory containing the label folders.

# bad_paths = []

# for image_path in img_paths:
#     try:
#       img_bytes = tf.io.read_file(image_path)
#       decoded_img = tf.io.decode_image(img_bytes)
#     except tf.errors.InvalidArgumentError as e:
#       print(f"Found bad path {image_path}...{e}")
#       bad_paths.append(image_path)

#     #print(f"{image_path}: OK")

# print("BAD PATHS:")
# for bad_path in bad_paths:
#     print(f"{bad_path}")

"""## Display Images"""

# Set the seed for reproducible results
SEED = 777
os.environ['PYTHONHASHSEED']=str(SEED)
os.environ['TF_CUDNN_DETERMINISTIC'] = '1'  # new flag for tf 2.0+
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

#import os
#from glob import glob
#from IPython.display import display  # display images

for i in range(len(IndoorImage_dir)):

    #image_file = list(img_dir.glob(IndoorImage[i]+'/*'))
    image_file = glob.glob(os.path.join(img_dir, IndoorImage_dir[i], '*'))
    #image_file = list(img_dir.glob(IndoorImage_dir[i]+'/*'))
    img = PIL.Image.open(str(image_file[0]))

    print(f'(Image size  = ({img.size[0]}, {img.size[1]}, {len(img.mode)}) ; IndoorsPlace = {IndoorImage_dir[i]})')
    display(img)

"""## Load & Pre-Process Images"""

# RESIZE images to consistent size for TensorFlow to be able to FIT using
# tf.keras.preprocessing.image_dataset_from_directory (instead of looping)
# which has 14 Possible parameters that can be set.
help(tf.keras.preprocessing.image_dataset_from_directory)

"""### Setup parameters used to load and process the images which are currently stored as files in a directory."""

# Set some parameters for tf.keras.preprocessing.image_dataset_from_directory
batch_size = 32
image_height = 256
image_width = 256
split = 0.2       # 0.2 values means 80% train and 20% test        # 0.9 for debug

"""###### TRAIN DATA creation"""

train_data = tf.keras.preprocessing.image_dataset_from_directory(
  img_dir,
  labels='inferred', # labels are generated from the directory structure
  label_mode='int',  #'int': means labels are encoded as integers (e.g. for sparse_categorical_crossentropy loss).
  validation_split= split,
  subset="training",
  seed= 1001, # set seed
  image_size=(image_height, image_width),
  batch_size=batch_size)

"""###### VALIDATION DATA creation"""

val_data = tf.keras.preprocessing.image_dataset_from_directory(
  img_dir,
  labels='inferred',
  label_mode='int',
  validation_split= split,
  subset="validation",
  seed=1001, # set seed
  image_size=(image_height, image_width),
  batch_size=batch_size)

"""## Visualize the Images"""

for img, lab in train_data.take(1):
    print(img[1].numpy().astype("uint16"))
    print(f'minimum = {np.amin(img[0].numpy().astype("uint16"))}, maximum = {np.amax(img[0].numpy().astype("uint16"))}')
    break

"""## Let's display a set of the now uniform images."""

# Plot one set of images in a space
# 4 images wide X 4 images tall

plt.figure(figsize=(12, 12))

for img, lab in train_data.take(1):
  for i in range(16):
    ax = plt.subplot(4, 4, i + 1)
    plt.imshow(img[i].numpy().astype("uint16"))
    # Map the label index to name
    plt.title(IndoorImage_dir[lab[i]])
    plt.axis("off")

"""## Check the shape and size of the image data and the labels."""

# Inspect the shapes of image batch and the labels batch
#type(train_data)
# the TF helps us creat the images and label in the dataset
for image_batch, labels_batch in train_data:
  print(f'image_batch.shape = {image_batch.shape} \nlabels_batch.shape = {labels_batch.shape } ')
  break

# image 4d (32batches, 256HEIGHT, 256WIDTH, 3CHANNELS ->COLORS- RGB)
# image_batch.shape = (32, 256, 256, 3)
# labels_batch.shape = (32,)

"""## Configure the Dataset for Better performance"""

# Apply caching, shuffle, and prefetch
# to help increase speed, reduce memory usage, and make processing more efficient

AUTOTUNE = tf.data.AUTOTUNE # Tune the value dynamically at runtime.

train_data = train_data.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_data = val_data.cache().prefetch(buffer_size=AUTOTUNE)

"""## Normalize the Data"""

# Typically the pixel values using 8 bits in the memoery, it denotes 2*2*..*2 =2^8 = 256 unique vlaues
# since Python starts from 0, 1, 2, ..., 255
#Normalize the pixel value to a number between 0 and 1 (instead of 0 and 255)
normalization_layer = tf.keras.layers.experimental.preprocessing.Rescaling(1.0/255.0)

"""Please build the CNN models based on the datasets. Then call the model fit funciton using something like

%%time
callback = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience= 5)
epochs= 100
history = model.fit(
  train_data,
  validation_data=val_data,
  epochs=epochs,
  callbacks=[callback], verbose = 1
)
"""

